name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Heritage
      id: heritage
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Heritage
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HERITAGE_RESULTS: "${{steps.heritage.outputs.result}}"
      with:
        runners: heritage
